spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: bae94116125!


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


logging.level:
  org.hibernate.SQL: debug


server:
  port: "${port:8080}"
  forward-headers-strategy: native