spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/blog
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug


server:
  port: $PORT