spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://be5fd3954d7f2f:d982de54@us-cdbr-east-04.cleardb.com/heroku_0d6cd585817159b?reconnect=true
    username: be5fd3954d7f2f
    password: d982de54




  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


logging.level:
  org.hibernate.SQL: debug


server:
  port: "${port:8080}"
  forward-headers-strategy: native